"""
Check database migration status.

Validates:
- Single Alembic head (no branch conflicts)
- No un-migrated model changes
- Current revision is up to date

Usage:
    python scripts/check_migrations.py

Exit codes:
    0 - All checks passed
    1 - Migration issues detected
"""

import subprocess
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from core import configure_logging, get_logger, LogContexts

logger = get_logger(LogContexts.SERVICE)


def check_single_head() -> bool:
    """Check that there's only one Alembic head."""
    result = subprocess.run(
        ["alembic", "heads"],
        capture_output=True,
        text=True,
        cwd=project_root
    )
    
    heads = [line for line in result.stdout.strip().split("\n") if line.strip()]
    head_count = len(heads)
    
    if head_count > 1:
        logger.error("multiple_alembic_heads_detected", count=head_count)
        for head in heads:
            logger.error("head", revision=head)
        return False
    
    if head_count == 0:
        logger.error("no_alembic_heads_found")
        return False
    
    logger.info("single_alembic_head_confirmed", revision=heads[0].split()[0] if heads else "none")
    return True


def check_unmigrated_changes() -> bool:
    """Check for model changes that haven't been migrated."""
    import tempfile
    import shutil
    
    # Create a temporary copy of alembic versions to test
    versions_dir = project_root / "alembic" / "versions"
    temp_dir = tempfile.mkdtemp()
    
    try:
        # Copy current versions
        temp_versions = Path(temp_dir) / "versions"
        temp_versions.mkdir()
        for f in versions_dir.glob("*.py"):
            if f.name != "__init__.py":
                shutil.copy(f, temp_versions)
        
        # Try to create autogenerated migration
        result = subprocess.run(
            ["alembic", "revision", "--autogenerate", "-m", "check_unmigrated"],
            capture_output=True,
            text=True,
            cwd=project_root
        )
        
        # Check if any new files were created
        new_files = list(versions_dir.glob("*_check_unmigrated.py"))
        
        if new_files:
            # Clean up the test migration
            for f in new_files:
                f.unlink()
            
            logger.error("un_migrated_model_changes_detected")
            logger.error("run_alembic_revision_autogenerate")
            return False
        
        logger.info("no_un_migrated_changes")
        return True
        
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def check_current_revision() -> bool:
    """Check current migration status."""
    result = subprocess.run(
        ["alembic", "current"],
        capture_output=True,
        text=True,
        cwd=project_root
    )
    
    if result.returncode != 0:
        logger.error("failed_to_check_current_revision", error=result.stderr)
        return False
    
    current = result.stdout.strip()
    if "head" in current.lower():
        logger.info("database_at_head_revision", revision=current.split()[0])
        return True
    else:
        logger.warning("database_not_at_head", current=current)
        return True  # Not an error, just informational


def main() -> int:
    """Run all migration checks."""
    configure_logging(level="INFO")
    
    logger.info("starting_migration_checks")
    
    all_passed = True
    
    checks = [
        ("single_head", check_single_head),
        ("current_revision", check_current_revision),
        ("unmigrated_changes", check_unmigrated_changes),
    ]
    
    for name, check_func in checks:
        logger.info(f"running_check", check=name)
        try:
            if not check_func():
                all_passed = False
                logger.error(f"check_failed", check=name)
            else:
                logger.info(f"check_passed", check=name)
        except Exception as e:
            all_passed = False
            logger.error(f"check_error", check=name, error=str(e))
    
    if all_passed:
        logger.info("all_migration_checks_passed")
        return 0
    else:
        logger.error("migration_checks_failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
